
# This file is used by Supabase CLI
project_id = "qkpjlfcpncvvjyzfolag"

[functions.audio-processor]
verify_jwt = false

[api]
port = 54321
schemas = []
extra_search_path = []
max_rows = 1000

[functions]
[functions.update-regional-playlists]
verify_jwt = false

[functions.geo-location]
verify_jwt = false

[functions.process-payout]
verify_jwt = true

